### ISSUE TITLE
unbound variable line 162

### ISSUE THREAD

**Issue by walidshaari** [pamoedom/ocp4upc#3]
I get this error, I am running from RHEL7.0 bastion host.  are there any other dependencies to run it accept of curl, dot and jq as well internet access?

[root@okd4-service ocp4upc]# ./ocp4upc.sh 4.3.20
[INFO] Checking prerequisites (curl jq dot)... [OK] 
[INFO] Errata provided (4.x.z mode), targeting '4.4' channels for upgrade path generation.
[INFO] Checking if '4.3.20' (amd64) is a valid release... [OK] 
./ocp4upc.sh: line 162: RES[@]: unbound variable

**Comment by pamoedom** [comment]
Hi Walid, I think the problem could be the BASH version on those early RHEL releases and how it manages the array boundaries.

You can safely bypass the issue just commenting out the 3rd line in the script as follows:

~~~
#set -o nounset
~~~

Regards.

**Comment by walidshaari** [comment]
thanks, yes that bypass the error

[root@okd4-service ocp4upc]# bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

[root@okd4-service ocp4upc]# ./ocp4upc.sh 4.3.3
[INFO] Checking prerequisites (curl jq dot)... [OK] 
[INFO] Errata provided (4.x.z mode), targeting '4.4' channels for upgrade path generation.
[INFO] Checking if '4.3.3' (amd64) is a valid release... [OK] 
[WARN] Discarding channel 'fast-4.4_amd64', it doesn't differ from 'stable-4.4_amd64'.
[WARN] Skipping channel 'stable-4.4_amd64', version '4.3.3' not found.
[ERROR] Version '4.3.3' not found (or not upgradable) within '4.4' channels. Aborting execution.
[INFO] TIP: try only with target release (e.g. 4.4) to check available versions.

[root@okd4-service ocp4upc]# ./ocp4upc.sh 4.3
[INFO] Checking prerequisites (curl jq dot)... [OK] 
[INFO] No errata provided (4.x mode), extracting default '4.3' channels.
[INFO] Checking if '4.3' (amd64) has valid channels... [OK] 
[INFO] Result exported as 'stable-4.3_amd64_def_20200615.svg'
[INFO] Result exported as 'fast-4.3_amd64_def_20200615.svg'

**Comment by pamoedom** [comment]
Yes, it's not an error but rather a warning, when using "set -o nounset", all unbound variables makes the script to abort.

This is not happening on recent BASH versions with that variable, I will investigate when I have some time, thanks for your input.

**NOTE**: 4.3.3 is not within 4.4 channels, you should extract first 4.4 default channels with `./ocp4upc.sh 4.4` to check the minimum 4.3.x upgradable version, which currently is 4.3.12.

Regards.

**Comment by walidshaari** [comment]
Thank you for developing this, it is very useful indeed

**Comment by pamoedom** [comment]
Thanks Walid, much appreciated your feedback :)

**Comment by pamoedom** [comment]
Hi Walid, I've decided to disable that extra 'nounset' check in the script to allow all BASH versions to properly work.

I will close this issue, thanks for your feedback.
